@extends('clinic.layout')
@section('title', __('Visit details'))
@section('content')
<div class="page-heading"><div><p class="eyebrow">{{ __('APPOINTMENT') }} #{{ $appointment->id }}</p><h1>{{ $appointment->patient->name }}</h1><p>{{ $appointment->doctor->name }} · <bdi>{{ $appointment->appointment_date->format('d M Y') }} / {{ substr($appointment->appointment_time,0,5) }}</bdi></p></div><span class="badge {{ $appointment->status }}">{{ __(ucfirst($appointment->status)) }}</span></div>
<div class="two-col"><section class="panel padded"><h2>{{ __('Visit information') }}</h2><dl><dt>{{ __('Patient email') }}</dt><dd>{{ $appointment->patient->email }}</dd><dt>{{ __('Phone') }}</dt><dd>{{ $appointment->patient->phone ?: '—' }}</dd><dt>{{ __('Reason for visit') }}</dt><dd class="pre-line">{{ $appointment->reason ?: __('Not provided') }}</dd></dl><div class="actions">@foreach(['confirmed'=>'Confirm visit','completed'=>'Complete visit','cancelled'=>'Cancel appointment'] as $status=>$label)
@continue(!in_array($appointment->status,['pending','confirmed']))
@continue($status==='confirmed' && $appointment->status!=='pending')
@continue($status==='completed' && ($appointment->status!=='confirmed' || !in_array(auth()->user()->role,['admin','doctor'])))
@continue(auth()->user()->role==='patient' && $status!=='cancelled')
<form method="post" action="{{ route('appointments.update',$appointment) }}" @if($status==='cancelled')data-confirm="{{ __('Cancel this appointment?') }}"@endif>@csrf @method('PATCH')<input type="hidden" name="status" value="{{ $status }}"><button class="button {{ $status==='cancelled'?'danger':'secondary' }}">{{ __($label) }}</button></form>@endforeach</div><a class="back-link" href="{{ route('appointments.index') }}">{{ __('Back to appointments') }}</a></section>
<section class="panel padded">@if(in_array(auth()->user()->role,['admin','doctor']))<h2>{{ __('Clinical notes') }}</h2><p class="muted">{{ __('Visible only to the treating doctor and administrators. Encrypted at rest.') }}</p><form method="post" action="{{ route('appointments.note',$appointment) }}" class="form-stack">@csrf<label class="field"><span>{{ __('Consultation record') }}</span><textarea name="notes" rows="9" maxlength="15000" required @disabled($appointment->status==='cancelled')>{{ old('notes',$note?->notes) }}</textarea></label>@if($appointment->status!=='cancelled')<button class="button">{{ __('Save clinical note') }}</button>@endif</form>@else<h2>{{ __('Your next step') }}</h2><p>{{ __('Please arrive a few minutes before your appointment and bring any relevant documents.') }}</p>@endif
@if($appointment->invoice && auth()->user()->role!=='doctor')<div class="fee"><span>{{ __('Invoice') }} #{{ $appointment->invoice->id }}</span><strong>{{ $appointment->invoice->amount }} {{ config('clinic.currency') }}</strong><a href="{{ route('invoices.show',$appointment->invoice) }}">{{ __('View invoice') }} ↗</a></div>@endif</section></div>
@if(in_array(auth()->user()->role,['admin','receptionist']) && in_array($appointment->status,['pending','confirmed']))
<section class="panel padded section-gap"><h2>{{ __('Reschedule visit') }}</h2><p>{{ __('Keep the same doctor and invoice. The new time must fit the doctor schedule and will need confirmation.') }}</p><form class="filters" method="post" action="{{ route('appointments.reschedule',$appointment) }}">@csrf @method('PATCH')<x-clinic-field name="appointment_date" label="Date" type="date" :value="$appointment->appointment_date->format('Y-m-d')" :min="now()->toDateString()" required/><x-clinic-field name="appointment_time" label="Time" type="time" :value="substr($appointment->appointment_time,0,5)" required/><button class="button secondary">{{ __('Reschedule visit') }}</button></form></section>
@endif
@endsection
