@extends('clinic.layout')
@section('title', __('Reports'))
@section('content')
<div class="page-heading"><div><p class="eyebrow">{{ __('THE BIGGER PICTURE') }}</p><h1>{{ __('Clinic performance') }}</h1><p>{{ __('Visits, collections and outstanding balances in one clear view.') }}</p></div><a class="button secondary" href="{{ route('reports.export', ['from'=>$from,'to'=>$to]) }}">{{ __('Export summary CSV') }}</a></div>
<section class="panel section-gap"><form class="filters" method="get"><x-clinic-field name="from" type="date" label="From date" :value="$from" required/><x-clinic-field name="to" type="date" label="Through date" :value="$to" required/><button class="button">{{ __('Apply dates') }}</button><a href="{{ route('reports.index') }}">{{ __('This month') }}</a></form></section>
<p class="muted report-period">{{ $from }} — {{ $to }} · {{ config('clinic.timezone') }} · {{ __('Maximum range: 366 days.') }}</p>
<div class="stats"><article class="stat"><span>{{ __('Scheduled visits') }}</span><strong>{{ $total }}</strong><small>{{ __('By appointment date, including cancellations') }}</small></article><article class="stat"><span>{{ __('Completed visits') }}</span><strong>{{ $counts['completed'] ?? 0 }}</strong><small>{{ __('By appointment date') }}</small></article><article class="stat"><span>{{ __('Payments collected') }}</span><strong class="money-value">{{ number_format($collected, 2) }}</strong><small>{{ config('clinic.currency') }} · {{ __('By payment date') }}</small></article><article class="stat"><span>{{ __('Outstanding balance') }}</span><strong class="money-value">{{ number_format($outstanding, 2) }}</strong><small>{{ config('clinic.currency') }} · {{ __('Unpaid visits in this date range') }}</small></article></div>
<div class="two-col"><section class="panel padded"><h2>{{ __('Visit status') }}</h2><div class="report-bars">@foreach(['pending','confirmed','completed','cancelled'] as $status)<div><div class="report-label"><span>{{ __(ucfirst($status)) }}</span><strong>{{ $counts[$status] ?? 0 }}</strong></div><meter min="0" max="{{ max(1,$total) }}" value="{{ $counts[$status] ?? 0 }}" aria-label="{{ __(ucfirst($status)) }}">{{ $counts[$status] ?? 0 }}</meter></div>@endforeach</div></section><section class="panel"><div class="panel-heading"><div><h2>{{ __('Collection breakdown') }}</h2><p>{{ __('Payments recorded within the selected dates.') }}</p></div></div><div class="table-wrap"><table><thead><tr><th>{{ __('Payment method') }}</th><th>{{ __('Payments') }}</th><th>{{ __('Amount') }} ({{ config('clinic.currency') }})</th></tr></thead><tbody>@forelse($methods as $method)<tr><td>{{ __(ucfirst($method->payment_method ?? 'Unknown')) }}</td><td>{{ $method->payments }}</td><td>{{ number_format($method->total,2) }}</td></tr>@empty<tr><td colspan="3" class="empty">{{ __('No payments recorded in this period.') }}</td></tr>@endforelse</tbody></table></div></section></div>
<section class="panel section-gap"><div class="panel-heading"><div><h2>{{ __('Daily activity') }}</h2><p>{{ __('Appointment counts include all statuses. Days without visits are omitted.') }}</p></div></div><div class="table-wrap report-daily"><table><thead><tr><th>{{ __('Date') }}</th><th>{{ __('Scheduled visits') }}</th><th>{{ __('Details') }}</th></tr></thead><tbody>@forelse($daily as $day)<tr><td>{{ $day->appointment_date->format('Y-m-d') }}</td><td>{{ $day->total }}</td><td><a href="{{ route('appointments.index',['date'=>$day->appointment_date->format('Y-m-d')]) }}">{{ __('View appointments') }}</a></td></tr>@empty<tr><td colspan="3" class="empty">{{ __('No appointments in this period.') }}</td></tr>@endforelse</tbody></table></div></section>
@endsection
